### ISSUE TITLE
Source of the ACAS Xu ONNX Files

### ISSUE THREAD

**Issue by hawkinsw** [stanleybak/AeroBenchVVPython#5]
Dr. Bak,

I was wondering how you sourced the ONNX files for the ACAS Xu branch? Did you generate those files yourself? Did you get them from another source? Any information you could provide would be incredibly helpful! 

Thank you!
Will

**Comment by stanleybak** [comment]
I believe I got them from [nnv](https://github.com/verivital/nnv). @trhoangdung do you know the history of the onnx version of the acasxu networks?

**Comment by trhoangdung** [comment]
Patrick is the one who passed the ACASXu networks from Stanford
people. @Patrick, can you answer this question?

I believe I got them from nnv <https://github.com/verivital/nnv>.
@trhoangdung <https://github.com/trhoangdung> do you know the history of
the onnx version of the acasxu networks?

**Comment by trhoangdung** [comment]
Good morning,

So that exists, but I believe the source of those ONNX networks come from here: https://github.com/dieman95/AcasXu/blob/master/other/functions/ToONNX.m, from the ACASXu repo. I do not remember exactly what the problem was, but it had to do with the export version (Opset version in MATLAB), so we had to change the way we did it.

How we did it, may not be the most ideal way to do it (as it requires more than one step), but we used the neural network parser https://github.com/verivital/nnvmt to convert the original files (Stanford format .nnet) to the NNV format (this file would convert all original networks to NNV
(https://github.com/dieman95/AcasXu/blob/master/other/functions/AcasxuNNVnet.m).
Then, we call this function https://github.com/dieman95/AcasXu/blob/master/other/functions/AcasxuONNX.m to convert all NNV-format networks to ONNX (this function calls the ToONNX function mentioned in the beginning to convert each file https://github.com/dieman95/AcasXu/blob/master/other/functions/ToONNX.m.

You can find all ACAS Xu networks in the different formats here:
 - Stanford .nnet format: https://github.com/dieman95/AcasXu/tree/master/networks/nnet
 - NNV format: https://github.com/dieman95/AcasXu/tree/master/networks/nnv_format
 - ONNX: https://github.com/dieman95/AcasXu/tree/master/networks/onnx

Best,
Diego


Diego Manzanas
Graduate Research Assistant
Institute for Software Integrated Systems
Department of Electrical Engineering and Computer Science
Vanderbilt University
________________________________

**Comment by hawkinsw** [comment]
Thank you everyone! This is really helpful for us. It seems like this has been fully resolved. I am going to close. Thanks again!

**Comment by trhoangdung** [comment]
Hello Tran,

I believe we converted the ACASXu networks to onnx using the Keras to ONNX converter. I wrote a parser from the Stanford format to Keras, and then from there they were parsed into Onnx. Diego correct me if I am wrong, but that's what I remember.

Warm Regards

Patrick Musau

Patrick Musau
Graduate Research Assistant
Verification and Validation for Intelligent and Trustworthy Autonomy Laboratory (VeriVITAL)
Department of Electrical Engineering and Computer Science
Vanderbilt University
https://pmusau17.github.io/
________________________________
